# 服务器配置
server:
  host: 127.0.0.1
  port: 7777

# RESTful API配置
api:
  base_url: http://127.0.0.1:5000/api
  timeout: 10
  poll_interval: 5
  long_poll_timeout: 30

# 串口配置
serial_ports:
  - name: COM 44
    description: WCH USB-SERIAL Ch A
    baudrate: 9600
    timeout: 1
    db_id: 1
  - name: COM 45
    description: WCH USB-SERIAL Ch C
    baudrate: 9600
    timeout: 1
    db_id: 2

# Modbus配置
modbus:
  request_delay: 0.5